### PR TITLE
WAB 2.4

### LINKED ISSUE #10: WAB 2.4 support
The script failed with WAB 2.4 default app.
Console error : 
``` 
TypeError: Cannot read property 'en' of undefined
    at Object.<anonymous> (main.js?wab_dv=2.4:536)
    at Object.forEach (init.js:70)
    at Object.registerWidgetFeatureActions (main.js?wab_dv=2.4:535)
    at Object.<anonymous> (main.js?wab_dv=2.4:536)
    at init.js:63
    at k (main.js?wab_dv=2.4:146)
    at Object.k [as visitElement] (main.js?wab_dv=2.4:146)
    at Object.b.visitElement (main.js?wab_dv=2.4:11)
    at Object.registerAllWidgetFeatureActions (main.js?wab_dv=2.4:536)
    at Object._onAppConfigLoaded (main.js?wab_dv=2.4:538) "TypeError: Cannot read property 'en' of undefined
```

### PR DESCRIPTION
**Pull request by g3r4n**
Build feature actions i18n labels in widgets-manifest.json
fix #10

### CODE REVIEW

**Comment by g3r4n** [comment]
I will test it on monday on a big project.
@crackernutter your feedback on this will great !

**Comment by gbochenek** [comment]
Is the feature action copy in this branch directly related to wab2.4, or does that apply to 2.3 as well?

**Comment by crackernutter** [comment]
Happy to help - I'll monitor the repo for when it's ready to test!

**Comment by g3r4n** [comment]
This fix support both versions. The version checking is a requirement of this PR

**Comment by g3r4n** [comment]
pushed in #27

**Pull request closed without merging**
