### PR TITLE
Use ESRI JS API 3.20

### PR DESCRIPTION
**Pull request by g3r4n**

### CODE REVIEW

**Comment by gbochenek** [comment]
WAB 2.3 still uses 3.19, so we want to stay there until we're able to provide full support for 2.4.

**Comment by g3r4n** [comment]
does detect WAB version and use specific bower would be a solution ?

**Comment by gbochenek** [comment]
I think so, but we would have to make sure the whole script supports 2.4, not just the bower bit.

**Comment by gbochenek** [comment]
Thinking this over and just getting 2.4 to work would be a start, we don't have to make it work with everything right away.  Users can still download 0.0.5, vs. 1.0.0 if they're looking for 2.3 support.

**Pull request closed without merging**
