### PR TITLE
Find api version from env.js

### PR DESCRIPTION
**Pull request by g3r4n**

### CODE REVIEW

**Comment by g3r4n** [comment]
fix #16

**Comment by gbochenek** [comment]
Very cool.  Thanks for all the contributions.

**Comment by gbochenek** [comment]
I just realized (after merging) that this doesn't fully account for everything.  There is a find replace at the end that removes the hardcoded env.js reference to the API.  We'll have to adjust for the check for this to work across multiple environments.

**Comment by g3r4n** [comment]
Can you be more specific ? Can you give a scenario where it will not working ?
If the find and replace occurred after we checked the apiversion that find.

**Comment by gbochenek** [comment]
Sure.  It happens in utilscripts.js.  Look for REPLACE.

I'm thinking we add the jsapi version as a parameter to that function.

**Comment by g3r4n** [comment]
You totally right i will fix this one !
btw i think we have to clean a little bit the code because there is some dead code like : 
https://github.com/gbochenek/esri-wab-build/blob/cfa15ee4ee7fa516e195c335d6ee1ff5a5a143ab/app/utilscripts.js#L390
where portalUrl is not used and config.json is read for nothing

**Comment by g3r4n** [comment]
in env.js there is no string like '//apiUrl=[POINT_TO_ARCGIS_API_FOR_JAVASCRIPT];' it's from the arcgis-js-api i think. so the entire function is useless.

**Pull request merged**
